name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: build exe
      run: cargo build --release
    - name: check file 
      run: |
        cd /home/runner/work/bend-language-server/bend-language-server/target/releases
        ls
      
    - uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.2
        release_name: Release ${{ github.ref }}
        tag: v0.1.0
        generate_release_notes: true
        files: /home/runner/work/bend-language-server/bend-language-server/target/releases/bend-language-server
